name: CD

on:
  push:
    branches: ['master', 'feat/cd']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.VTEX_GITHUB_BOT_TOKEN }}

      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: WhoAmI
        run: |
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
          lerna whoami

      - name: Configure CI Git User
        run: |
          git config user.name vtexgithubbot
          git config user.email vtexgithubbot@github.com

      # TODO: We should be able to remove this extra steop and save some action money
      - name: Build
        run: yarn build

      - name: Publish package
        run: |
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
          lerna publish minor --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
