name: CD

on:
  push:
    branches: ['master', 'feat/cd']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Configure CI Git User
        run: |
          git config --global user.name 'faststore bot'
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

      # TODO: We should be able to remove this extra build and save some action money
      - name: Build
        run: yarn build

      - name: Publish package
        run: lerna publish minor --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
