name: CD

on:
  push:
    branches: ['master']

jobs:
  publish:
    name: Release faststore

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Use Node ${{ matrix.node }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - uses: smartlyio/lerna-publish-action@v2
        with:
          bump: major
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
